### ISSUE TITLE
Questions about generating 'sulc.affine.ico6' files and 'indices.pt'

### ISSUE THREAD

**Issue by lincong8722** [mohamedasuliman/DDR#1]
Dear friends:
I have two problems. The first problem is that some rotation matrices will be generated after running DDR_affine_train.py, but the file '.L.sulc.affine.ico6.shape.gii' will be used when running DDR_coarse_train.py, Is this file manually generated through the generated rotation matrix?
The second question is that some pt files cannot be used when I want to use the neigh_ver/indices* files. Can you provide the indices.pt file when control_ico_coar=6?
Looking forward to your reply.

**Comment by ruoyu-z** [comment]
You can use wb-command [-surface-apply-affine](https://www.humanconnectome.org/software/workbench-command/-surface-apply-affine) command to rotate the surface file.

**About indices.pt，I have same problem when I load indices_red_4_8.pt.**
```
Traceback (most recent call last):
  File "/home/postgraduate/zhangruoyu21/DDR_main/DDR_fine_train.py", line 88, in <module>
    num_labels=num_labels_coar, device=device)
  File "/home/postgraduate/zhangruoyu21/DDR_main/models/DDR_coarse_model.py", line 234, in __init__
    device=device)        
  File "/home/postgraduate/zhangruoyu21/DDR_main/models/DDR_coarse_stn.py", line 82, in __init__
    indices_matrix = torch.load('neigh_ver/indices_red_'+str(control_ico)+'_'+str(labels_ico)+'.pt')
  File "/home/postgraduate/zhangruoyu21/.conda/envs/DDR/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/postgraduate/zhangruoyu21/.conda/envs/DDR/lib/python3.7/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

```
I think this pt file is incomplete. I have tried to use git lft and direct zip file via my web browser.But the error was not resolved.Where do these files come from? Have they been uploaded correctly?
Looking forward to your reply.

**Comment by ruoyu-z** [comment]
@mohamedasuliman Is there any other way to download the files in the neigh_ver folder? I tried to use git-lfs, but it could not be downloaded correctly.

**Comment by ruoyu-z** [comment]
I tried to use _git lfs fetch_
```
fetch: Fetching reference refs/heads/main
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/mohamedasuliman/DDR.git/info/lfs'
```
Does this indicate that your bandwidth is insufficient?I would be happy to pay for one git-lfs pack
